#!/bin/sh
: "${ffp:=ffprobe -v error -select_streams v:0}"
: "${showF:=-show_entries format=size,duration}"
: "${showS:=-show_entries stream=width,height,avg_frame_rate,r_frame_rate}"
: "${outF:=-of default=noprint_wrappers=1}"
tmFmt='(dur<10?"%3.1f":"%3.0f")'
szFmt='(size<1e9?"%5.3f":"%5.2f")'
nh=1
[ "${noh-unset}" = unset ] && {         # if not no header
  printf "%4s %4s %4s %3s %5s %5s %6s %s\n" CBpp Wdth Hght Min Fps GB mDate name
  nh=0; }
for f
do
  mt=$(stat -c%Y "$f"); (               # ffprobe already emits awk-compatible..
  echo 'BEGIN{'                         #..syntax=>Convert awk print of desired.
  $ffp $showF $showS $outF "$f"         # Emits lines like width=3840
  echo '}END{
fr   = avg_frame_rate != 0/0 ? avg_frame_rate : r_frame_rate
raw  = 0.125*fr*duration*width*height   # 1/8 => CBits/px->bytes
dur  = duration/60                      # seconds -> minutes
date = strftime("%y%m%d", mt)           # format as a Date
printf(".%03d %4d %4d " '$tmFmt' " %.2f " '$szFmt' " %6s",
       size/raw*1000, width, height, dur, fr, size/1e9, date)
if (noh) printf("\\n"); else printf(" %s\\n", nm)}') | # tee /tmp/j.awk |
  awk -v nm="$f" -v mt=$mt -v noh="$nh" -f- # STD: -f- to run stdin
done    # Could also capture $ffp in a $(), but that leads to quoting pain.
